INSERT INTO tb_produtos(name, preco) VALUES ('Motorola Moto G9 Power', 2499);
INSERT INTO tb_produtos(name, preco) VALUES ('iPhone 13', 7999);
INSERT INTO tb_produtos(name, preco) VALUES ('Samsung Galaxy S21 Ultra', 1199);
INSERT INTO tb_produtos(name, preco) VALUES ('Google Pixel 6', 6999);
INSERT INTO tb_produtos(name, preco) VALUES ('OnePlus 10 Pro', 999);
INSERT INTO tb_produtos(name, preco) VALUES ('Xiaomi Redmi 10', 1999);
INSERT INTO tb_produtos(name, preco) VALUES ('Sony Xperia 1 III', 999);
INSERT INTO tb_produtos(name, preco) VALUES ('Huawei P50 Pro', 1099);
INSERT INTO tb_produtos(name, preco) VALUES ('LG Velvet', 699);
INSERT INTO tb_produtos(name, preco) VALUES ('Nokia 8.3', 599);
INSERT INTO tb_produtos(name, preco) VALUES ('Asus Zenfone 8', 6999);
INSERT INTO tb_produtos(name, preco) VALUES ('Realme GT', 3299);
INSERT INTO tb_produtos(name, preco) VALUES ('Oppo Find X3 Pro', 8999);
INSERT INTO tb_produtos(name, preco) VALUES ('BlackBerry Key2', 49999);
INSERT INTO tb_produtos(name, preco) VALUES ('Lenovo Legion Phone Duel', 6999);
INSERT INTO tb_produtos(name, preco) VALUES ('ZTE Axon 30 Ultra', 5999);
INSERT INTO tb_produtos(name, preco) VALUES ('Vivo X60 Pro', 6999);
INSERT INTO tb_produtos(name, preco) VALUES ('Meizu 18', 5999);
INSERT INTO tb_produtos(name, preco) VALUES ('Tecno Camon 17 Pro', 1999);
INSERT INTO tb_produtos(name, preco) VALUES ('Infinix Note 10 Pro', 2499);


INSERT INTO tb_comprador(name, dinheiroDisp, product_id) VALUES ('Kauê',2500,3);
INSERT INTO tb_comprador(name, dinheiro_disp, product_id) VALUES ('Rita',4500,1);
INSERT INTO tb_comprador(name, dinheiro_disp, product_id) VALUES ('Lucineide',5500,2);
INSERT INTO tb_comprador(name, dinheiro_disp, product_id) VALUES ('Luciana', 1800, 7);
INSERT INTO tb_comprador(name, dinheiro_disp, product_id) VALUES ('Felipe', 1100, 8);
INSERT INTO tb_comprador(name, dinheiro_disp, product_id) VALUES ('Marina', 900, 9);
INSERT INTO tb_comprador(name, dinheiro_disp, product_id) VALUES ('Vinícius', 1200, 10);
INSERT INTO tb_comprador(name, dinheiro_disp, product_id) VALUES ('Carla', 1600, 11);
INSERT INTO tb_comprador(name, dinheiro_disp, product_id) VALUES ('Guilherme', 1400, 12);
INSERT INTO tb_comprador(name, dinheiro_disp, product_id) VALUES ('Rafaela', 750, 13);
INSERT INTO tb_comprador(name, dinheiro_disp, product_id) VALUES ('Mariana', 1700, 14);
INSERT INTO tb_comprador(name, dinheiro_disp, product_id) VALUES ('Gustavo', 950, 15);
INSERT INTO tb_comprador(name, dinheiro_disp, product_id) VALUES ('Larissa', 1250, 16);
INSERT INTO tb_comprador(name, dinheiro_disp, product_id) VALUES ('Pedro', 1350, 17);
INSERT INTO tb_comprador(name, dinheiro_disp, product_id) VALUES ('Camila', 2000, 1);
INSERT INTO tb_comprador(name, dinheiro_disp, product_id) VALUES ('Roberto', 1000, 2);
INSERT INTO tb_comprador(name, dinheiro_disp, product_id) VALUES ('Carolina', 800, 3);
INSERT INTO tb_comprador(name, dinheiro_disp, product_id) VALUES ('Leonardo', 2000, 4);
INSERT INTO tb_comprador(name, dinheiro_disp, product_id) VALUES ('Amanda', 1200, 5);
INSERT INTO tb_comprador(name, dinheiro_disp, product_id) VALUES ('José', 1300, 6);
