INSERT INTO TB_PRODUTOS(NAME,PRECO) VALUES ('MOTOG 54',1500);
INSERT INTO TB_PRODUTOS(NAME,PRECO) VALUES ('MOTOG Super',3500);
INSERT INTO TB_PRODUTOS(NAME,PRECO) VALUES ('MOTOG One',2500);

INSERT INTO TB_COMPRADOR(NAME,DINHEIRO_DISP,PRODUCT_ID) VALUES ('Kauê',2500,3);
INSERT INTO TB_COMPRADOR(NAME,DINHEIRO_DISP,PRODUCT_ID) VALUES ('Rita',4500,1);
INSERT INTO TB_COMPRADOR(NAME,DINHEIRO_DISP,PRODUCT_ID) VALUES ('Lucineide',5500,2);


